name: json-codec
version: 0.0.0.0


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - attoparsec
    - bytestring
    - text

tests:
  json-codec-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - bytestring
    - genvalidity
    - genvalidity-sydtest
    - genvalidity-text
    - json-codec
    - sydtest
    - text
